server.port: 8081

api:
  version: "v1"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gym?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: postgres
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: update
        jdbc:
          lob:
            non_contextual_creation: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER